[package]
name = "warp-backend"
version = "0.1.0"
authors = ["atmaram"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tambola-lib = { path = "../tambola-lib" }
